### ISSUE TITLE
Add legendary set tooltips to Epic/blue sets

### ISSUE THREAD

**Issue by ledigbick** [marius00/iagd#101]
For example:
![TrozanToolTip](https://user-images.githubusercontent.com/27318368/101088775-d5ade800-35bc-11eb-8554-4b10d143e53b.PNG)

I like to clean up the stash every few sessions, and dismantle the worse rolls of duplicate items. Sometimes you can have 4 or 5 duplicates of the same item, but the entire set is only 2 or 3 different items at most. The current alternative is to search for an item's set and transfer duplicates from there, then clear up the search bar and scroll from the beginning to where the original set item was; quite uncomfortable.
Thanks in advance.

**Comment by marius00** [comment]
What exactly are you requesting?

You want the same tooltip on Blue items?

**Comment by ledigbick** [comment]
Yes. 🙂

**Comment by marius00** [comment]
Fixed about 3 weeks ago.
