### ISSUE TITLE
Mutiple "Conduit xxx Whispers" can't show and transfer all

### ISSUE THREAD

**Issue by devil40xxx** [marius00/iagd#104]
There is something wrong in handlering the Legendary Amulet series "Conduit xxx Whispers".

If you put mutiple (like 30 )in and It can only show one in the type.

 And when you push  "transfer all". It only go out one  and you have to refresh the index to get another. 

BTW  mPestilence  Dreeg Amulet has the same problem.

**Comment by marius00** [comment]
Which version of IA?

**Comment by marius00** [comment]
If you can reproduce the issue on the latest version of IA, attach your export.ias here so I can import the item and attempt to reproduce it.

**Comment by devil40xxx** [comment]
![pic
![pic](https://user-images.githubusercontent.com/44527608/103470117-d054e080-4da8-11eb-8969-c212c7bb3fba.png)
](https://user-images.githubusercontent.com/44527608/103470108-be733d80-4da8-11eb-8f4b-20767434f021.png)

**Comment by marius00** [comment]
Can you attach your export.ias?

**Comment by devil40xxx** [comment]
here it is&nbsp;


thx for your concern&nbsp;!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "marius00/iagd"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月3日(星期天) 晚上7:05
收件人:&nbsp;"marius00/iagd"<iagd@noreply.github.com&gt;;
抄送:&nbsp;"曾"<237269@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [marius00/iagd] Mutiple "Conduit xxx Whispers" can't show and transfer all (#104)





 
Can you attach your export.ias?

**Comment by marius00** [comment]
Does not seem like it got attached, can you retry? On the issue itself, not via email.

**Comment by devil40xxx** [comment]
OK

[export.zip](https://github.com/marius00/iagd/files/5761507/export.zip)

**Comment by marius00** [comment]
Fixed in 1.2.7675.18845
