### ISSUE TITLE
Text is spelled backwards

### ISSUE THREAD

**Issue by krissrex** [marius00/iagd#114]
I started the program as non-administrator. It also failed to find any items.
The pc is English/Norwegian locale, and should not be backwards (Arabic etc).  
It worked as expected when I ran it as administrator.

![image](https://user-images.githubusercontent.com/7364831/113327865-c301b080-931b-11eb-9064-c002bd0de868.png)

![image](https://user-images.githubusercontent.com/7364831/113327910-d3b22680-931b-11eb-9997-4e9bf89a7609.png)

**Comment by marius00** [comment]
Known issue that seems to happen only on the 1st of April every year. Quite odd.

A known workarounds is restarting IA.
