### ISSUE TITLE
Clear search field when ctrl+backspace is pressed

### ISSUE THREAD

**Issue by krissrex** [marius00/iagd#115]
**Description:**
On most programs, ctrl+backspace will clear the previous word from a text input: `"abc 123  |" -> ctrl+backspace -> "abc "`.

**Expected:** Pressing will delete the trailing space and the word left of the cursor.

**Actual:** A character `` (char code 127, `DELETE`) is inserted, which looks like `[]`.

**Comment by marius00** [comment]
Fixed in 1.2.7770.17852

Repository will reflect this... at some point. My ISP has decided that git and ssh is evil, and is blocking all outgoing connections to github. Will sync via my cellphone later on.

**Comment by krissrex** [comment]
> git and ssh

You can use HTTP by doing `git remote set-url origin https://github.com/marius00/iagd.git` if git over ssh is the problem.

Thanks for the fix!

**Comment by marius00** [comment]
I took the approach of calling, messaging and emailing my ISP until they fixed the issue on their end.

Blocking SSH and git affects more than just this one project ;)
