### ISSUE TITLE
Feature request: Filter for craftable items.

### ISSUE THREAD

**Issue by swasher** [marius00/iagd#145]
I think, it will be convinment for have a filter that show only craftable items.

**Comment by marius00** [comment]
All items that can theoretically be crafted, that you own? Or all items that YOU can craft, that you own?
(Or just all items that can be crafted regardless of you owning them?)

**Comment by marius00** [comment]
Not something like https://grimdawn.evilsoft.net/gdcraft/ you're after?

**Comment by swasher** [comment]
I mean items that can be crafted at blacksmither, they show as at picture
![image](https://user-images.githubusercontent.com/1525918/149622347-90e2a005-3895-4c4c-98a3-71ad783ac345.png)
(sorry for foreign language, hope you understand)
Also, I can help you with russian translation, you you need.

**Comment by marius00** [comment]
>  Also, I can help you with russian translation, if you need.

The russian translation is the "tags_ia.txt" file inside the russian zip file.
Any changes needs to be submitted to the russian community over at https://forums.crateentertainment.com/t/russian-translation/28381/61

It's not integrated in IA, it all depends on community translations =)

**Comment by marius00** [comment]
As for the actual issue.. I'll try to get it added today.

**Comment by marius00** [comment]
Added.

Will be included in whichever release is next.
