### ISSUE TITLE
Instaloot: allow adjust this feature

### ISSUE THREAD

**Issue by swasher** [marius00/iagd#155]
Hello Marius!
Thanks for new feature! 
Is it possible to add some adjust setting - on/off this one, and on/off message "ITEM LOOTED by item assistance"? 

When I want moving several dozen items after good raid, and choose what move to stash, and what to sell, this banner show on top every item, when I read item description.

Оn the other side, it convinent to see what item I moved to stash already. May be I misstakenly move it, and then I can return item to my character.

**Comment by marius00** [comment]
I'll see about getting a toggle added for it.

The "Item looted by", is the issue that its displayed, or that it's displayed a gazillion times? I was thinking of maybe throttling it a bit.

**Comment by swasher** [comment]
I mean, that "Item looted by" lay over item description, like this
![image](https://user-images.githubusercontent.com/1525918/150652826-dd00c3b4-aa8d-4251-8bc4-4065c0f1f18d.png)
My personal preference - it is old behavior, when first place all item to last stash, and then looted. May be cool, when character go away from stash, item looted and banner shown "13 item looted" :wink:

**Comment by marius00** [comment]
Try the latest version, it should be easier in terms of that.. the text.

The old "walk away from stash" etc was never really a solution I wanted, the reason you need to walk away, is because if you re-open the stash while IA is looting, your risk causing issues. It's kind of a hack to ensure that the user does not interact with the stash while IA is.. never really how things were meant to be =)

**Comment by abclution** [comment]
I just ran an update on IA and now everything put in the IA tab instantly disappears. I guess this is the new instaloot feature? 
I love the text overlay, but I really preferred the "walk away" method as I am quite clumsy with my loot transfer skills.

 Anyway to revert?

**Comment by marius00** [comment]
> Anyway to revert?

Not currently

**Comment by marius00** [comment]
Added support in 1.3.8071.28441 for disabling instaloot
