### ISSUE TITLE
Unable to launch GD Item Assistant

### ISSUE THREAD

**Issue by DestrockQc** [marius00/iagd#175]
Hi, I don't know what I do wrong but it doesn't want to launch at all.

- cloud save disabled both in steam and in game
- I manually deleted my cloud saves
- GD Item Assistant is installed
- I installed the most recent Visual C++
- I have the Microsoft .NET Framework 4.7.2
- I added an exception for the whole Steam folder in BitDefender and GD Item Assistant also
- On the GD Item Assistant shortcut properties, I use the run as admin and disable DPI

Do I forget something ? wtf... When I try launching it nothing happen... When I check the tutorial video I see nothing special to do. You install it, launch it...

**Comment by marius00** [comment]
Can you provide me with the log file from `%appdata%\..\local\evilsoft\iagd` ?

**Comment by marius00** [comment]
EDIT: Redownload IA, there was a bug in how 1.3.8141.12075 was compiled, causing IA to not launch properly.

**Comment by DestrockQc** [comment]
Ok, now it's installed but it bug... I check the tutorial video again, I do what I have to do, I tried adding 3 green items in the 6th tab, GDIS find it, I can see it. I move away from my stash, I click on the transfer to stash button, I go check my stash, from every tabs and they are no where, they disappeared. I restarted the game, still nothing.

**Comment by marius00** [comment]
I'm sure someone on the discord can help =)

**Comment by DestrockQc** [comment]
I boycott discord they give our data to google and host our personal informations on google servers.

**Comment by DestrockQc** [comment]
I just made a mule to make room in my chest. My 5th tab was not empty, I was wondering if it was the cause of the problem cause in the video he use an empty tab. Now my 5th and my 6th are empty.

I started GD Item Assistant before starting the game. I added 1 junk green item to the last tab : https://imgur.com/a/dCafNdS

It was written I was standing too close but I was there : https://imgur.com/a/UOiERhI

I played with this option and it woke up https://imgur.com/a/Sd7SWr1

I clicked on "transfer to stash" and it looked as it worked : https://imgur.com/a/XXAWaLV

But in game I have nothing : https://imgur.com/a/EV0kUEi I checked every tabs, the chest is no where.

**Comment by DestrockQc** [comment]
It started working, I don't have much idea why. I installed GD Stash and java, maybe it unbugged something, or I verified my steam files while searching how to fix my screen tearing problem (unfixable...)
