### ISSUE TITLE
Moving an Item from the GDIA to Stash result in error message but still works as intended

### ISSUE THREAD

**Issue by Shashahan** [marius00/iagd#22]
When i move an item from GDIA to the stash i get the error message 
"Cannot deposit item, please ensure Stash 3 is empty" but it still works. 
![2018-06-13 21_44_15- tool grim dawn item assistant - page 176 - grim dawn forums](https://user-images.githubusercontent.com/39258796/41377281-e4d29e4a-6f5b-11e8-825c-e7fc0ac65857.png)

I am using GD 1.0.6.1 with the Ashes of Malmouth expansion.

Best Regards,
Olaf

**Comment by marius00** [comment]
No longer relevant with v1.4
