### ISSUE TITLE
IA deletes itself ????

### ISSUE THREAD

**Issue by marius00** [marius00/iagd#32]
Initially I've discarded this purely as an "outside factor" issue.. and I still think it's that.. but bears looking into.

Essentially, some users reports that IA crashes and then when they try to start it again, it's not there anymore. It has been deleted.

I cannot fathom how IA could possibly be responsible for such behavior, but it bears looking into.

**Ref the latest report**: "Hello, I wanted to report a persistent error. It's been several months since I last played GD, but yesterday I decided to pick it up again. After playing for a while, I started your item assistant, which immediately caused both the game and the assistant to close to desktop. I tried running them again, but the assistant's .exe was gone. I tried reinstalling but it wouldnt let me unless I restarted my pc first. This happens every time I try to run both at the same time. This also happens if I start the assistant first, then GD. The moment GD opens, both crash and the .exe gets deleted. I also tried doing a backup of the .exe and pasting it once it got deleted, but the entire installation folder gets locked until I restart my pc (says I dont have permission). Assistant works fine after restart and pasting the backup .exe, but crashes again on GD startup."

**Comment by Ronald-IE** [comment]
Same problem here, IA crashes on GD startup. Cause in my case is Bitdefender killing it and moving files to quarantine.

**Comment by marius00** [comment]
Ah, timing makes sense. IA Injects a DLL into Grim Dawn to monitor the stash status (open/closed)

**Comment by marius00** [comment]
The user which initiated this issue (on the forum) reports that his anti virus has silently quarantined IA without any notifications. The user found it in the anti virus logs.

Mainly two things triggers anti virus software on IA:
* Automatic updates (an executable which downloads new unknown code from their view)
* DLL Injection (injecting code into other processes)

There is no obvious "easy fix", but could investigate to see if it's possible to detect these anti virus programs and request a whitelist dialogue or similar. (Or detecting anti virus might be suspicious in itself?)

At a minimum, it would be great if the user could be notified of what's going on, so the end user can take appropriate action without needing support.
