### ISSUE TITLE
Search item issue [Russian]

### ISSUE THREAD

**Issue by swasher** [marius00/iagd#33]
First, you do very useful and impressive work, thank you!
I play and use IA in russian. There is search issue with capital letters. For example, I want to find "Воля Бисмиэль". When I type "Воля", IA show 3 item. Notice, it's case insensitive ("Воля" and "воля" do same).
![image](https://user-images.githubusercontent.com/1525918/52909608-6f978a00-329c-11e9-928a-25aa97d814f1.png)

Next I start type "Бисмиэль".
![image](https://user-images.githubusercontent.com/1525918/52909642-f8162a80-329c-11e9-932f-bc1b9bbabcce.png)

I try "Бисмиэль" without "Воля":
![image](https://user-images.githubusercontent.com/1525918/52909646-15e38f80-329d-11e9-9a8b-a6936137e69a.png)

As result, I can't find item, which contain capital letters in name.
I think, it can be SQLite search issue described [here](https://stackoverflow.com/a/973665/1334825).
Believe me, its very annoying, and do me crazy, when i can't find my items! )) Please please fix it!

**Comment by marius00** [comment]
Well written bug report! 

That could indeed be the issue.. [This might be a solution, for that specific query](https://stackoverflow.com/questions/4201583/can-i-customize-collation-of-query-results-in-nhibernate)

**Comment by marius00** [comment]
1. Update to http://grimdawn.dreamcrash.org/ia/GDItemAssistantBeta.exe
2. Go to the database/mods tab
3. Click "Update item stats" in the bottom right corner
4. Attempt to search again with lower/upper case.

**Comment by swasher** [comment]
Thank you very much! Now working well!
