### ISSUE TITLE
tags_ia on github contains errors

### ISSUE THREAD

**Issue by marius00** [marius00/iagd#34]
The tags_ia.txt file distributed to community translators contains some errors, it appears to be partially Portuguese, rather than fully English. 

Wrong file checked in perhaps..

**Comment by Bonivur** [comment]
Also it has double same tags : 

iatag_ui_backup_location=Online Backup
iatag_ui_backup_location=Local Backup

whereas the first one should be iatag_ui_online_backup

**Comment by marius00** [comment]
Should now contain the correct tags.

IA will also dump all the tags to %appdata%\..\local\evilsoft\iagd\tags_ia.template.txt on startup.
