### ISSUE TITLE
looting problem

### ISSUE THREAD

**Issue by Fratos** [marius00/iagd#41]
i stashed Mythical Soullance and it is gone!. items will take from stash tap 6 but i can't find them in GD Item Assistant. 
i have the same problem with the beta version.

**Comment by marius00** [comment]
IA keeps backups of your transfer stashes at: %appdata%\..\local\evilsoft\iagd\backup

So you can still restore the item from an old transfer stash.
I'll try to get my hands on a _Mythical Soullance_ to test how IA interacts with it.

**Comment by marius00** [comment]
Update to the latest version of IA, and parse the database again.
Check if you can find the Mythical item now. IA should finally be able to recognize it.

**Comment by marius00** [comment]
Several players (and me) have confirmed that the issue is now resolved. IA was unable to properly parse the name of the item.

If you still cannot find the item, just re-open this issue.
