### ISSUE TITLE
Import old GDIA backup file, unable to parse items

### ISSUE THREAD

**Issue by jayteez** [marius00/iagd#43]
I imported a GDIA backup file and now have  a mix of 809 unknowns and my previously saved items from the backup. Not sure why it was unable to parse some items from the backup but not others? I will attach my log file and the backup file I used.
[Saturday.zip](https://github.com/marius00/iagd/files/3020087/Saturday.zip)
[log.txt](https://github.com/marius00/iagd/files/3020102/log.txt)

**Comment by marius00** [comment]
Update to the latest version of IA and retry.
Fixed some issues with parsing items.

**Comment by jayteez** [comment]
Thank you very much, all resolved now. GDIA is indispensable and I can't imagine playing Grim Dawn without it.
