### ISSUE TITLE
GDIA won't loot new MIs

### ISSUE THREAD

**Issue by jackrare** [marius00/iagd#44]
GDIA does not loot any of the new monster infrequents dropped in forgotten gods. It notes that the items are possibly bugged or duplicates. Typically when I get this message the item actually gets looted into GDIA and it dupes the item and so i just sell the one it won't loot. However in this case it doesn't loot the items out of the stash tab at all.

It has looted 5 FG rare items and listed those under unkown item. So it is able to loot some FG items, but it won't take any of the rare MIs.

Here is an image of the MI graphics
https://i.imgur.com/U9ftXHE.png

Here is an image of the error from 1 of the new MIs
https://i.imgur.com/Y10l1YH.png

And here is what the log shows after it doesn't take the items shown in the first image
https://i.imgur.com/ABiQmAy.png

I have tried individual items and the full stash

Please let me know if I can provide any more information as i'm not really sure what to add.

**Comment by marius00** [comment]
Do you have the transfer.gst file?
Would help if I don't have to go farm new items =)

**Comment by jackrare** [comment]
[Thursday.zip](https://github.com/marius00/iagd/files/3021258/Thursday.zip)

I'm hoping the transfer.gst in that folder is what you're asking for. I was unable to drag just that file in so i just put the zip in. By the way all of those MIs have vanished lol. They are not in gdia or in game any longer. It's not a huge deal to me, but I figured it may be important for diagnostic.

**Comment by marius00** [comment]
That does indeed contain the transfer file. I'll check it later today.

**Comment by marius00** [comment]
Re-test on the latest version of IA.
1. Update
2. Load database
3. 🎉

**Comment by jackrare** [comment]
Working now. Thank you!
