### ISSUE TITLE
IA lists FG epic/legendary items as "Unknown"

### ISSUE THREAD

**Issue by desophos** [marius00/iagd#47]
Epic and legendary items introduced with Forgotten Gods appear as one stack of an "Unknown" item. They can be transferred to and from IA with no problems. I've attached my [transfer.gst file](https://github.com/marius00/iagd/files/3021259/transfer.zip) with Skytear Hat in the 4th tab, which is one of the items that has this problem. I'll update the attached file with future problematic items I find.

**Comment by marius00** [comment]
Re-test on the latest version of IA.
1. Update
2. Load database
3. 🎉

**Comment by firvain** [comment]
[log.txt](https://github.com/marius00/iagd/files/3024143/log.txt)
1)version 1.2.7025.36391 from 27/03/2019 load database does nothing for this issue
2) also new version beta cant parse older (pre exp) ias files all shows unknown (tried aslo completely clean install) --- maybe not related? --- install on top of old version parses pre exp items 
also check this  [http://prntscr.com/n4st2b](url) dont know if its relevant/ok

**Comment by marius00** [comment]
That is true, but does the version of 29/03/2019 fix it?

**Comment by firvain** [comment]
yep it fixed it ty
