### ISSUE TITLE
Improve feedback: Duplicate/Bugged items

### ISSUE THREAD

**Issue by marius00** [marius00/iagd#50]
When an item is not being looted due to being a duplicate, IA should link to http://grimdawn.dreamcrash.org/ia/help.html?q=DuplicateItem

Somehow..

**Comment by marius00** [comment]
Minor improvement added in the latest version.

**Comment by iThinker** [comment]
I've encountered this issues somehow, and it is not very clear how it happens and what to do. Is it safe to sell all "duplicated" items?
I tried to search for one item, GDIA showed that item with different stats (base?), but when I retrieved the item from GDIA it indeed had identical stats.
Is it possible maybe to have a setting to just automatically delete duplicated items from Stash? It might be opt-in. But it would give a seamless experience.

**Comment by marius00** [comment]
Basically:
1) IA "loots" the item (IA create a copy in its own database)
2) IA deletes the item from the transfer stash (make a new stash file, without the "looted" item)

What goes wrong sometimes is in step #3, where you re-open the stash, and Grim Dawn reads the stash from **memory** instead of from file, causing GD to think the item still exists, and voila duplicate.

Now, I totally agree with your suggestion, it was up for a vote sometime last year, if IA should automatically delete the items, or simply warn the user (or allow item duplication).

**Comment by iThinker** [comment]
My concern was that when I searched the item in IA, I saw different stats (base?) so I was like "Well, I have a different item here", but when I pulled item into stash, it was clearly a duplicate. Now my related question is. Is it expected that IA shows different items stats? Does it show item base stats?
Also how does IA check if item is a duplicate? Purely by comparing all stats? If the answer is yes, then I would be pretty confident in deleting items (even manually).

**Comment by marius00** [comment]
IA does not know the stats of items, which is why it only shows the base stats.
IA Compares the item by looking at Prefix, Suffix, base item and the seed.

Aside from components which share the same seed, that leaves a 1/4 billion chance of ever getting the same seed (ever, not even on this specific item..) So lets call it an even 1/100bn chance IA is actually wrong.  -- But if there's a bug in IA, that could of course be an issue.

**Comment by iThinker** [comment]
I think it is fine. Now when I understand better I am more OK. 
I wonder why item stats are unknown to IA? Other tools cannot know stats either?

**Comment by marius00** [comment]
Being addressed, as good as it can anyways.
First beta of this was released today.

To answer the last question, no tools currently know the stats. 
The time investment required to reverse engineer it, without help from Create, is simply not worth it.
