### ISSUE TITLE
Oathkeeper filter

### ISSUE THREAD

**Issue by marius00** [marius00/iagd#53]
Users keeps complaining about oathkeeper missing.

Not experienced it myself, but would be nice to find steps to reproduce it, add it to the FAQ at least.

**Comment by okainov** [comment]
Looks like already implemented? At least I see "Oathkeeper" in "Classes" view in the main window

**Comment by marius00** [comment]
Indeed, I have not been able to reproduce the issue where Oathkeeper is either missing, or the checkbox is not functioning.

**Comment by marius00** [comment]
Now hardcoded in IA.
Mod classes are still loaded dynamically.
