### ISSUE TITLE
IA is spamming stash distance

### ISSUE THREAD

**Issue by marius00** [marius00/iagd#67]
1. Open IA
2. Open GD
3. Open ingame stash
4. Close ingame stash
5. Close GD
6. IA keeps whining about distance from stash, since the player never moved away.

**Comment by marius00** [comment]
Clarification: This issue is related to IA not detecting "game closed" as "far from stash", not the spam itself.

**Comment by Eradev** [comment]
Seems to be fixed?

**Comment by marius00** [comment]
No longer relevant in v1.4
