### ISSUE TITLE
Item research - In Content

### ISSUE THREAD

**Issue by neooblaster** [marius00/iagd#69]
Hello Marius

I open this issue as feature request :
Do you think that will be possible in the future to search items by **skill modifier**.
There are already standard filters on class/element/kind of items, but nothing allow us to search for instance "item with skill modifier for Panetti's Replicating Missile".

I think that could be resource consumer to search in all the player database.
To enhance the research, maybe when item added, you can create an index only on skill modifier (while reading attributes) and make research in the index to retrieve all corresponding items ?

Thank a lot. I suppose you have so many work in front of you with requests ;)

Kindly regards,
Neoblaster.

**Comment by marius00** [comment]
Partially supported, just search for "Replicating Missile" in the free text searchbox.

**Comment by marius00** [comment]
No updated on the issue. I assume the freetext search is sufficient.
