### ISSUE TITLE
Can't swap between different versions of game

### ISSUE THREAD

**Issue by dks99455** [marius00/iagd#71]
Hiya,

After loading the database for Forgotten Gods install, IA will only detect Forgotten Gods even when DLCs are disabled. 

https://www.reddit.com/r/Grimdawn/comments/bqpjiu/item_assistant_cant_swap_between_dlc_versions/

**Comment by marius00** [comment]
![image](https://user-images.githubusercontent.com/5671213/130182657-263f0113-e9df-4a66-b2d4-a5e81b1b19ae.png)

**Comment by marius00** [comment]
Addressed in 1.2.7907.24527
