### ISSUE TITLE
"Tabs" are not tabs

### ISSUE THREAD

**Issue by okainov** [marius00/iagd#82]
Tools shows tabs-like view however when one clicks on the tab it opens links in the browser. This is bad UX experience - tabs should behave like tabs, not like links.

![image](https://user-images.githubusercontent.com/918446/66269533-c365dc00-e849-11e9-9281-7f64e3ac5340.png)

**Comment by marius00** [comment]
I'll try to set aside time for it.
There used to be tabs, but no more.

**Comment by marius00** [comment]
8365ce73b02d8d34118c85e89ace7a99be9ff33a
