### ISSUE TITLE
Some skills description is missing

### ISSUE THREAD

**Issue by okainov** [marius00/iagd#84]
Seems like for *some* skills description is missing. I.e.:

```
Could not find stats for the skill records/skills/itemskillsgdx1/skillmodifiers/monsterinfrequents/mace1h_b013_forcewave.dbr
Could not find stats for the skill records/skills/itemskillsgdx2/skillmodifiers/mi/medal_b201_aegis.dbr
```

**Comment by marius00** [comment]
Do you have an item export file with item names?

(export.ias)

**Comment by okainov** [comment]
Not sure what do you mean, I have the game installed (Steam version), but it doesn't contain `export.ias` file

**Comment by marius00** [comment]
Closing issue due to lack of reply/followup.
