### ISSUE TITLE
Buddy Sync Filter Hardcore

### ISSUE THREAD

**Issue by silencshadow** [marius00/iagd#86]
Hello,
if i filter to Vanilla HC the complete stash of my buddy is visible ... HC and non HC. I think this is a bug? Because i just want to see HC items ... or non HC ;-)

regards.

**Comment by marius00** [comment]
Will look into it. Buddy sync has some.. deficiencies..

**Comment by marius00** [comment]
Resolved in 1.2.7266.14007 / 1ac5dbf8050a5392621f78381c31a9334739df91
Re-open this issue if it turns out to not be the case.


http://grimdawn.dreamcrash.org/ia/latest.php - Always the latest version, always.
