### ISSUE TITLE
Show set bonuses

### ISSUE THREAD

**Issue by marius00** [marius00/iagd#9]
IA does not show setbonuses on items.
Add the functionality, optional via settings.

**Comment by swasher** [comment]
I think, there is no need to show all set bonuses. Show set bonuses will lead to readability degradation from screen. But you can specify the membership of a particular set, somethink like this:
![image](https://user-images.githubusercontent.com/1525918/52909954-842a5100-32a1-11e9-8aa0-dfdfd3244173.png)
If user click a set name, IA show all set item which he has.
It will be very convenient!

**Comment by marius00** [comment]
Good suggestion.

However, I have no immediate plans on doing the set bonuses.
Time is ever an issue, though hopefully someone else will pick this one up.

**Comment by marius00** [comment]
For whomever ends up implementing this, here's some queries to help identify set items:
`-- Easy query to find all sets:
SELECT *, (SELECT Name FROM DatabaseItem_v2 WHERE id_databaseitem = S.id_databaseitem) as SetName from DatabaseItemStat_v2 S where Stat = 'itemSetName' ORDER BY textvalue


-- Find name for a given set:
SELECT T.name FROM DatabaseItemStat_v2 S, ItemTag T
WHERE id_databaseitem IN (
	SELECT id_databaseitem FROM DatabaseItem_v2 WHERE baserecord = 'records/items/lootsets/itemset_c001.dbr'
)
AND S.stat = 'setName'
AND T.tag = S.TextValue


-- Combining these two we get:

SELECT *, 
(
	SELECT T.name FROM DatabaseItemStat_v2 ST, ItemTag T WHERE id_databaseitem IN (SELECT id_databaseitem FROM DatabaseItem_v2 db WHERE db.baserecord = S.TextValue)
	AND ST.stat = 'setName' AND T.tag = ST.TextValue
) as SetName, 
(SELECT Name FROM DatabaseItem_v2 WHERE id_databaseitem = S.id_databaseitem) as ItemName 

from DatabaseItemStat_v2 S 
where Stat = 'itemSetName' 
AND SetName IS NOT NULL
ORDER BY textvalue

-- Discover all the stats of a specific set (in this case set 7355112)
SELECT * FROM DatabaseItemStat_v2 WHERE id_databaseitem = (
	SELECT id_databaseitem FROM DatabaseItem_v2 WHERE baserecord = (
		SELECT TextValue FROM DatabaseItemStat_v2 S WHERE id_databaseitem = 7355112 AND stat = 'setMembers'
	)
)
ORDER BY TextValue
`

A set is much like an item, and IA should be able to render a set roughly as well as it renders an item. A set has triggers, skills etc just like items do.

**Comment by marius00** [comment]
The most efficient thing would probably be to pre-compute the sets and set them on initial load, and then simply check if each rendered item is in a set.

If in a set: List the set name, and make it clickable to show other items in the set (and how many of each)

**Comment by marius00** [comment]
Thinking something ala:
* Sets are exposed as JSON to the web ui
* When rendering an item, ask some service (in JS) if it's part of a set
* Render which set its in, clickable
* OnClick => Poll C# for all items owned in this set
* Render a view of the set, its bonuses and which items are owned / missing.

Polling on click will help with performance (lazy load), and should be a very simple query when its on a specific set basis.

**Comment by mightyBroccoli** [comment]
Are there news on this issue? It would be nice to have something like that inside IA

**Comment by marius00** [comment]
No more progress just yet.
I am still in the middle of moving cross-continents. 

I do intend for there to be progress on this task, though it will come after certain bugfixes and QoL fixes.

**Comment by marius00** [comment]
> Are there news on this issue? It would be nice to have something like that inside IA

Partially implemented a few patches ago.

**Comment by marius00** [comment]
Now longer relevant after the introduction of real item stats
