### ISSUE TITLE
Missing "Maximum All Resistances" in IA

### ISSUE THREAD

**Issue by ledigbick** [marius00/iagd#99]
Shard of Menhir in GT:
![SoMGT](https://user-images.githubusercontent.com/27318368/100642063-f5d17300-3340-11eb-8d05-59c3ac975317.PNG)

Shard of Menhir in IA:
![SoMIAPNG](https://user-images.githubusercontent.com/27318368/100642082-fd911780-3340-11eb-9fc3-6eddf4189b41.PNG)

**Comment by marius00** [comment]
Fixed in 1.2.7639.29758
